# Generated by Django 4.0.4 on 2022-05-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_profile_bio_alter_profile_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='has_party',
            field=models.BooleanField(default=False),
        ),
    ]
