# Generated by Django 4.0.4 on 2022-05-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_event_has_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.event'),
        ),
    ]
