# Generated by Django 4.0.4 on 2022-05-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingparty',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
