# Generated by Django 4.0.4 on 2022-05-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_photo_event'),
        ('main_app', '0007_alter_viewingparty_end_time'),
    ]

    operations = [
    ]
