# Generated by Django 4.0.4 on 2022-05-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20220503_1446'),
        ('main_app', '0009_alter_photo_profile'),
    ]

    operations = [
    ]
