# Generated by Django 4.0.4 on 2022-05-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20220503_1522'),
        ('main_app', '0010_merge_20220503_1658'),
    ]

    operations = [
    ]
