# Generated by Django 4.0.4 on 2022-05-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20220504_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingparty',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_viewing_party', to='main_app.event'),
            preserve_default=False,
        ),
    ]
