# Generated by Django 4.0.4 on 2022-05-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_viewingparty_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='best_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
