# Generated by Django 4.0.4 on 2022-05-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_event_best_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='best_date',
            field=models.DateField(null=True),
        ),
    ]
