# Generated by Django 4.0.4 on 2022-05-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.viewingparty'),
        ),
    ]
