# Generated by Django 4.0.4 on 2022-05-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_photo_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='types',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('L', 'Lunar'), ('S', 'Solar'), ('C', 'Conjunction'), ('P', 'Planetary'), ('M', 'Meteor'), ('C', 'Comet'), ('AD', 'Asteroid'), ('AM', 'Astronomy'), ('SC', 'Spacecraft')], default='L', max_length=2),
        ),
    ]
